# Update all submodules (and check out the same branch as the main repo if it exists)
tasks:
  - before: git submodule foreach "git checkout $(git symbolic-ref --short -q HEAD) 2>/dev/null; git pull --rebase origin"
